name: build-web

on:
  workflow_call:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Nodejs
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Nodejs build web
      - run: |
          npm install
          npm run build
        working-directory: pisugar-webui

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pisugar-web
          path: |
            pisugar-webui/dist
          if-no-files-found: warn
